[build]
  functions = "netlify/functions"
  publish = "public" # Or any other directory that Netlify can publish, even if empty
  plugins = [] # Explicitly disable all plugins

[functions]
  node_bundler = "esbuild" # Recommended bundler for Netlify functions
