[build]
  functions = "netlify/functions"
  publish = "public" # Or any other directory that Netlify can publish, even if empty

[functions]
  node_bundler = "esbuild" # Recommended bundler for Netlify functions

[[plugins]]
  package = "@netlify/plugin-nextjs"
  disable = true
